version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: care-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-1234}
      MYSQL_DATABASE: ${DB_NAME:-care}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: care-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql-data:
